Listing.organisation join
OpenCatalogi/opencatalogi pull request #142
Opened 2024-08-09 15:08 UTC by bbrands02

2024-08-09 15:09 UTC, bbrands02 commented on lib/Db/ListingMapper.php
> +use OCA\OpenCatalogi\Db\Organisation;
haal ik nog weg

2024-08-09 15:09 UTC, bbrands02 commented on lib/Db/Listing.php
> +use OCA\OpenCatalogi\Db\Organisation;
haal ik nog weg

2024-08-12 08:52 UTC, rjzondervan requested changes

2024-08-12 08:52 UTC, rjzondervan commented on src/store/modules/directory.js
> +                                    console.log(this.listingList)
Console.log

2024-08-12 08:54 UTC, WilcoLouwerse approved these changes

2024-08-12 08:54 UTC, WilcoLouwerse commented on src/store/modules/directory.js
> +                                    console.log(this.listingList)
console log

2024-08-12 09:29 UTC, WilcoLouwerse approved these changes

2025-06-20 14:53 UTC, merged